make: program1.cpp program2.cpp program3.cpp
	g++ -o program1 program1.cpp -Wall -std=c++14
	g++ -o program2 program2.cpp -Wall -std=c++14
	g++ -o program3 program3.cpp -Wall -std=c++14
run3:
	./program1 filex.txt filey.txt output1.txt
	./program2 filex.txt filey.txt output2.txt
	./program3 filex.txt filey.txt output3.txt
